export const ORDER = {
  id: "order_1LS2MCKjjG8w6pC3NpRoZhWv",
  object: "order",
  amount_subtotal: 14400,
  amount_total: 14900,
  application: "ca_M8TywDe4OxLRtBjNtsQLoPKJoRR34MGQ",
  automatic_tax: { enabled: false, status: null },
  billing_details: {
    address: {
      city: "London",
      country: "GB",
      line1: "Flat 3, 224 Tooting High Street, Tooting",
      line2: null,
      postal_code: "SW17 0SG",
      state: null,
    },
    email: "zach.molony@gmail.com",
    name: "Zach Molony",
    phone: null,
  },
  client_permissions: {
    billing_details: "disallow",
    promotion_codes: "disallow",
    shipping_details: "disallow",
  },
  client_secret: "order_1LS2MCKjjG8w6pC3NpRoZhWv_secret_0LlbHgqlvkUdLlJeHnWOPsSHg00h18u4qmG",
  created: 1659374684,
  currency: "gbp",
  customer: null,
  description: null,
  discounts: [],
  ip_address: null,
  livemode: false,
  metadata: { developer_fee: "720", shipping_status: "unshipped" },
  payment: {
    payment_intent: "pi_3LS2MQKjjG8w6pC31QeFxKO5",
    settings: {
      application_fee_amount: 720,
      automatic_payment_methods: { enabled: false },
      payment_method_options: null,
      payment_method_types: ["card"],
      return_url: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      transfer_data: null,
    },
    status: "complete",
  },
  shipping_cost: {
    amount_subtotal: 500,
    amount_tax: 0,
    amount_total: 500,
    shipping_rate: "shr_1KksGwKjjG8w6pC39WekF6sQ",
  },
  shipping_details: {
    address: {
      city: "London",
      country: "GB",
      line1: "Flat 3, 224 Tooting High Street, Tooting",
      line2: null,
      postal_code: "SW17 0SG",
      state: null,
    },
    name: "Zach Molony",
    phone: null,
  },
  status: "complete",
  tax_details: { tax_exempt: "none", tax_ids: [] },
  total_details: { amount_discount: 0, amount_shipping: 500, amount_tax: 0 },
  line_items: [
    {
      id: "li_1LS2MCKjjG8w6pC3GCedlyAG",
      object: "item",
      amount_discount: 0,
      amount_subtotal: 9700,
      amount_tax: 0,
      amount_total: 9700,
      currency: "gbp",
      description: "Hannya Knit",
      price: {
        id: "price_1LQ8T7KjjG8w6pC3sq4nK8zZ",
        object: "price",
        active: false,
        billing_scheme: "per_unit",
        created: 1658921521,
        currency: "gbp",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: "prod_JwFcxrLo0lbpCF",
        recurring: null,
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "one_time",
        unit_amount: 9700,
        unit_amount_decimal: "9700",
      },
      product: {
        id: "prod_JwFcxrLo0lbpCF",
        object: "product",
        active: true,
        attributes: [],
        created: 1627518537,
        default_price: "price_1JIN7OKjjG8w6pC3B0FJb51V",
        description: null,
        images: [
          "https://files.stripe.com/links/MDB8YWNjdF8xOHZxZnNLampHOHc2cEMzfGZsX3Rlc3RfRWdFVVRTUmVLUE9vZmhiWFU4SExEdmE500U3yWN0x5",
        ],
        livemode: false,
        metadata: {},
        name: "Hannya Knit",
        package_dimensions: null,
        shippable: null,
        statement_descriptor: null,
        tax_code: null,
        type: "service",
        unit_label: null,
        updated: 1658759239,
        url: null,
      },
      quantity: 1,
    },
    {
      id: "li_1LS2MCKjjG8w6pC3hJWYT6oD",
      object: "item",
      amount_discount: 0,
      amount_subtotal: 4700,
      amount_tax: 0,
      amount_total: 4700,
      currency: "gbp",
      description: "Inner Mind Tee",
      price: {
        id: "price_1LS2MBKjjG8w6pC31P7zwdau",
        object: "price",
        active: false,
        billing_scheme: "per_unit",
        created: 1659374683,
        currency: "gbp",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: "prod_JwBuWmUrM0WNmH",
        recurring: null,
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "one_time",
        unit_amount: 4700,
        unit_amount_decimal: "4700",
      },
      product: {
        id: "prod_JwBuWmUrM0WNmH",
        object: "product",
        active: true,
        attributes: [],
        created: 1627504713,
        default_price: "price_1JIJWQKjjG8w6pC34WeaFvzQ",
        description: null,
        images: [
          "https://files.stripe.com/links/MDB8YWNjdF8xOHZxZnNLampHOHc2cEMzfGZsX3Rlc3RfeDVDZmFtc3E4RG03UFdXZjlueEt4TzFr00H1j7YR07",
        ],
        livemode: false,
        metadata: {},
        name: "Inner Mind Tee",
        package_dimensions: null,
        shippable: null,
        statement_descriptor: null,
        tax_code: null,
        type: "service",
        unit_label: null,
        updated: 1651789074,
        url: null,
      },
      quantity: 1,
    },
  ],
};
